### ISSUE TITLE
vim.fs.joinpath not available on stable

### ISSUE THREAD

**Issue by tim-harding** [lawrence-laz/neotest-zig#10]
Running `require 'neotest-zig'` throws an error in log.lua on line 35 because the `vim.fs.joinpath` API is only available on nightly.

**Comment by lawrence-laz** [comment]
Is it just `joinpath` function, or the whole `vim.fs` that is not available in tagged version? Because this pluging uses `vim.fs` quite a lot, so not sure if it's better to create polyfills for these functions, or just wait for nvim 0.10 release, which seems 97% done.

I currently away, so cannot resolve this right away

**Comment by tim-harding** [comment]
The API is so similar to `vim.fs.normalize` that I don't think it's even necessary to polyfill. Hopefully this PR will look alright to you.

**Comment by lawrence-laz** [comment]
Merged, thanks for the PR!
Does the plugin work ok on 0.9.5 for you now?

**Comment by tim-harding** [comment]
Works for me! Thanks for merging.
